version: "3"

services:
  rails_backend:
    image: rails_backend:${RELEASE_VERSION}
    command: bundle exec puma -C config/puma.rb -e production
    restart: always
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - PORT=5000
      - RAILS_SERVE_STATIC_FILES=false
      - RELEASE_VERSION=$RELEASE_VERSION
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$LINODE_IP
    networks:
      - default

  richardhowellpeak_nginx:
    image: richardhowellpeak_nginx:${RELEASE_VERSION}
    container_name: richardhowellpeak_nginx
    build: 
      context: ./src/rails-backend
      dockerfile: ./nginx.Dockerfile
      args:
        SECRET_KEY_BASE: $SECRET_KEY_BASE
    restart: always
    ports:
      - 9000:80
    networks:
      - proxy-net
      - default

networks:
  proxy-net:
    external: true