version: "3"

services:
  old_rails_app:
    image: old_rails_app:${RELEASE_VERSION}
    command: bundle exec puma -C config/puma.rb -e production
    restart: always
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - PORT=5000
    networks:
      - default

  nginx_richardhowellpeak:
    image: nginx_richardhowellpeak:${RELEASE_VERSION}
    container_name: nginx_richardhowellpeak
    build: 
      context: ./src/old-rails-7
      dockerfile: ./nginx.Dockerfile
      args:
        SECRET_KEY_BASE: $SECRET_KEY_BASE
    restart: always
    ports:
      - 9000:80
    networks:
      - proxy-net
      - default

networks:
  proxy-net:
    external: true