version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    # environment:
    #   REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./prometheus:/etc/prometheus