version: '3.2'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.4.2
    ports:
      - 9200:9200 
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    command: bin/elasticsearch
    volumes:
      - ./docker-data/elasticsearch:/usr/share/elasticsearch/data
      - ./docker-data/elasticsearch-tmp:/tmp
    networks:
      - elk

  logstash:
    image: logstash:8.4.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    # environment:
    #   LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.4.3
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

# volumes:
#   elasticsearch: