source 'https://rubygems.org'

gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
gem 'prometheus-client'
gem 'sinatra'
gem 'puma'
gem "async", "~> 1.30"

gem "async-http", "~> 0.59.2"
