name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    # - uses: actions/checkout@v1
    - name: Install Dart
      uses: google/dart@2.17.6
    - name: Install app dependencies
      run: cd src/backend/authentication && dart pub get
    - name: Test app
      run: dart test --coverage
