name: Backend Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dart
        uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: cd src/backend/authentication && dart pub get
      - name: Test app
        run: cd src/backend/authentication && dart test
