name: Deploy

on:
  # Will run after a successful test
  repository_dispatch:
    types: [deploy]
  # Will run if manually triggered
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Which docker tag to use
        required: true
env:
  # This is for the build-stage of the asset pipeline
  SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
  RELEASE_VERSION: ${{ github.event.client_payload.release_version || github.event.inputs.releaseVersion }}
  LINODE_IP: ${{ secrets.LINODE_IP }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start ssh agent
        uses: frankdejonge/use-ssh-agent@1.0.0
        
      - name: Install ssh keys
        run: ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      
      - name: Install known hosts
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/known_hosts
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> $HOME/.ssh/known_hosts
          chmod 644 $HOME/.ssh/known_hosts

      - name: Deploy the Docker images
        run: docker-compose -H "ssh://richardhp@${{ secrets.LINODE_IP }}" -f ./docker-compose-deploy.yaml up -d --remove-orphans
