name: Deploy
on:
  # This will only run if Test workflow completes and we are on master branch.
  # workflow_run:
  #   workflows: ['Test']
  #   types: ['completed']
  #   branches: [ 'master' ]
  # Will run if we create a new release
  # release:
  #   types: [created]
  push: ['master']
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

    - name: Start ssh agent
        uses: frankdejonge/use-ssh-agent@1.0.0
      
    - name: Install ssh keys
      run: ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    
    - name: Install known hosts
      run: |
        mkdir -p $HOME/.ssh
        touch $HOME/.ssh/known_hosts
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> $HOME/.ssh/known_hosts
        chmod 644 $HOME/.ssh/known_hosts

    - name: Build the Docker images
      run: docker-compose -H ssh://richardhp@139.162.203.91 -f ./docker-compose.yml -f ./docker-compose-prod.yml build --force --no-cache

    # - name: Stop the Docker images
    #   run: docker-compose -H ssh://richardhp@139.162.203.91 -f ./docker-compose.yml -f ./docker-compose-prod.yml down

    - name: Deploy the Docker images
      run: docker-compose -H ssh://richardhp@139.162.203.91 -f ./docker-compose.yml -f ./docker-compose-prod.yml up -d --build --force-recreate
