name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Test app
        run: cd src/frontend && flutter test

# chromedriver --port=4444 && flutter drive --driver=test_driver/integration_test.dart --target=test_integration/app_test.dart -d web-server
