name: Backend Tests
on:
  # Will run after a successful build
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: deploy
          client-payload: '{ "release_version": "${{ github.event.client_payload.release_version  }}" }'